Vagrant.configure("2") do |config|
  (2..7).each do |i|
    config.vm.define "machine-#{i}" do |machine|
      machine.vm.box = "centos/7"
      machine.vm.box_version = "1804.02"
      machine.vm.hostname = "machine-#{i}"

      machine.vm.network "private_network", ip: "10.20.1.#{i}"

      machine.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 512]
        v.customize ["modifyvm", :id, "--name", "machine-#{i}"]
        v.customize ["guestproperty", "set", :id, "/stack","worldstack"]
      end

      machine.vm.provision "shell", path: 'lib/provision.sh'


    end

  end
end
