Vagrant.configure("2") do |config|

  config.vm.box = "devopsgroup-io/windows_server-2012r2-standard-amd64-nocm"

  config.vm.communicator="winrm"
  config.vm.network "private_network", ip: "10.20.1.10"
  config.vm.guest = :windows
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 512]
  end
end
